[profile.default]
src = "src"
out = "out"
optimizer = true
optimizer_runs = 44_444_444
via_ir = true
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"}]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
[fmt]
line_length = 100
tab_width = 2
quote_style = 'single'
number_underscore = 'thousands'
sort_imports = true
