# Script name
name: Run Foundry lint

# Prerequisites for execution: any actions with the pool-request
on: [pull_request]

jobs:
  lint:
    name: Run Foundry lint
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Install Foundry
        uses: KyberNetwork/foundry-toolchain@master
        with:
          version: v1.5.0

      - name: Run lint
        run: forge fmt --check
        id: lint