# Script name
name: Run Foundry tests
# Prerequisites for execution: any actions with the pool-request
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  foundry_test:
    name: Run Foundry tests
    runs-on: ${{ github.event.repository.private && 'self-hosted' || 'ubuntu-latest' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GH_PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Yarn
        run: npm install --global yarn

      - name: Run yarn
        run: yarn install --frozen-lockfile

      - name: Install Foundry
        uses: KyberNetwork/foundry-toolchain@master
        with:
          version: v1.5.0

      - name: Run Foundry tests
        run: forge test -vvv
        id: test